import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // {
    //   type: 'autogenerated',
    //   dirName: '.'
    // }
    {
      type: 'category',
      label: 'Documentação',
      collapsible: false,
      link: {
        type: 'generated-index',
        title: 'Introdução',
        description: 'Selecione abaixo a linguagem de programação que deseja utilizar o AmazonasDataHub:',
        slug: '/', // "/docs/"
        keywords: ['guias', 'r', 'python'],
      },
      items: [
        {
          type: 'category',
          label: 'Python',
          link: { type: 'generated-index', description: "Documentação do AmazonasDataHub na versão em Python" },
          items: [{ type: 'autogenerated', dirName: 'python' }],
        },
        {
          type: 'category',
          label: 'R',
          link: { type: 'generated-index', description: "Documentação do AmazonasDataHub na versão em R" },
          items: [{ type: 'autogenerated', dirName: 'r' }],
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
