
---
title: "agriculture_amazonas"
format: docusaurus-md
---

# agriculture_amazonas

Dados de produção vegetal do Instituto de Desenvolvimento Agropecuário e Florestal Sustentável do Amazonas (2023)

### Descrição

Esse banco de dados que é a consolidação de dados dos relatórios de atividades do IDAM, traz dados de produção vegetal de cultivos no qual esse instituto consideram prioritários.

### Uso

```{r, eval = FALSE}
agriculture_amazonas
```

### Formato

‘agriculture_amazonas’ Um data frame com 1072 linhas e 13 colunas:

#### municipality

Município

#### local_unit

Unidade Local do IDAM

#### n_beneficiary

Número de beneficiários assistidos

#### planted

Área plantada em hectares (ha)

#### harvested

Área colhida em hectares (ha)

#### production

Produção (na unidade de medida - measure)

#### estimated_n_beneficiary

Estimativa para o número de beneficiários

#### estimated_planted

Estimativa para a área plantada (ha)

#### estimated_harvested

Estimativa para a área colhida (ha)

#### estimated_production

Estimativa para a produção (na unidade de medida - measure)

#### measure

Unidade de medida da produção


#### cultivation

Cultivo

#### year

Ano do cultivo

### Fonte

https://www.idam.am.gov.br/biblioteca/relatorio-de-atividades-rat-23-2/
