---
title: "Bases de Dados"
format: docusaurus-md
---

# Documentação dos Dados

Caso não tenha instalado o `amazonasdatahub`, veja a página de instalação: [Instalação do amazonasdatahub](../instalacao).

Veja a documentação de cada base de dados pelos links abaixo.

| Função | Descrição |
| :----- |:--------- |
|[agriculture_amazonas](./agriculture_amazonas)|Plant production data from the Institute of Sustainable Agricultural and Forestry Development of Amazonas - IDAM (2023)|
|[aids_amazonas](./aids_amazonas)|A dataset of AIDS occurrences from 2011 to 2023 in Amazonas|
|[humidity_manaus](./humidity_manaus) |Time series with Extreme Values of Limited Range|
|[malaria_amazonas](./malaria_amazonas)|An integrated dataset of malaria notifications in the state of Amazonas|
|[gdp_amazonas](./gdp_amazonas)|Gross Domestic Product - GDP of Amazonas|
|[rionegro_amazonas](./rionegro_amazonas)|A dataset of the Rio Negro River (Amazonas) level from 2003 to 2023|
|[srl_muni](./srl_muni)| Physical literacy and reading performance of amazonian schoolchildren: an association study|
